language: python
python:
  - "3.8"
  # - "nightly"
  # TODO: add nightly back when this issue is fixed: https://github.com/cython/cython/issues/3266
arch:
  - arm64
addons:
  apt:
    sources:
      - sourceline: 'ppa:openjdk-r/ppa'
      - sourceline: 'deb http://www.apache.org/dist/cassandra/debian 311x main'
        key_url: &apache-key https://www.apache.org/dist/cassandra/KEYS
      - sourceline: 'deb-src http://www.apache.org/dist/cassandra/debian 311x main'
        key_url: *apache-key
    packages:
      - cython3
      - openjdk-8-jdk
      - cassandra
services:
  - rpc_address: 0.0.0.0
  - start_native_transport:true
  - native_transport_port:9042
  - cassandra
  - mongodb
install:
  - echo ===========Cassandra Installation======================
  - sudo apt update
  - sudo apt install openjdk-8-jdk
  - java -version
  - sudo apt install apt-transport-https
  - wget -q -O - https://www.apache.org/dist/cassandra/KEYS | sudo apt-key add -
  - sudo sh -c 'echo "deb http://www.apache.org/dist/cassandra/debian 311x main" > /etc/apt/sources.list.d/cassandra.list'
  - sudo apt update
  - sudo apt install cassandra
  #- tail -f logs/system.log
  #- nodetool status
  - cqlsh
  - UPDATE system.local SET cluster_name = 'Linuxize Cluster' WHERE KEY = 'local';
  - cluster_name: 'Linuxize Cluster'
  - nodetool flush system
  - sudo systemctl restart cassandra
  # Disable Cassandra optional extensions (faster testing).
  - export CASS_DRIVER_NO_EXTENSIONS=1
  - pip install -e .[test]
  - if [[ $TRAVIS_PYTHON_VERSION == '3.6' || $TRAVIS_PYTHON_VERSION == '3.7' || $TRAVIS_PYTHON_VERSION == '3.8' || $TRAVIS_PYTHON_VERSION == 'nightly' ]]; then pip install -e .[experimental_aio]; fi
before_script:
  - ifconfig | grep -Eo 'inet (addr:)?([0-9]*\.){3}[0-9]*' | grep -Eo '([0-9]*\.){3}[0-9]*' | grep -v '127.0.0.1'
  - sudo systemctl restart cassandra.service
  - sudo service cassandra status
  - bash travis/wait_for_cassandra.sh
  - bash travis/wait_for_cassandra.sh
script:
  # Run non aio tests first because Python versions before 3.6 does not support aio.
  - export DO_TEST_CASSANDRA=true
  - nosetests --exclude-dir=test/aio
  # Run aio tests.
  - export DO_TEST_MONGO=true
  - if [[ $TRAVIS_PYTHON_VERSION == '3.6' || $TRAVIS_PYTHON_VERSION == '3.7' || $TRAVIS_PYTHON_VERSION == '3.8' || $TRAVIS_PYTHON_VERSION == 'nightly' ]]; then nosetests test.aio; fi
