language: python

python:
  - "3.8"
  # - "nightly"
  # TODO: add nightly back when this issue is fixed: https://github.com/cython/cython/issues/3266
  
arch:
  - arm64

addons:
  apt:
    sources:
      - sourceline: 'ppa:openjdk-r/ppa'
      - sourceline: 'deb http://www.apache.org/dist/cassandra/debian 311x main' 
        key_url: &apache-key https://www.apache.org/dist/cassandra/KEYS
      - sourceline: 'deb-src http://www.apache.org/dist/cassandra/debian 311x main'
        key_url: *apache-key
    packages:
      - cython3
      - openjdk-8-jdk
      - cassandra
services:
  - cassandra
  - mongodb
install:
  #Installation of mongodb
  - apt update && apt upgrade -y
  - apt install apt-transport-https ca-certificates curl software-properties-common
  - curl -fsSL https://download.docker.com/linux/ubuntu/gpg | apt-key add -
  - sudo add-apt-repository "deb [arch=arm64] https://download.docker.com/linux/ubuntu $(lsb_release -cs) stable"
  - apt update
  - apt-cache policy docker-ce
  - apt install docker-ce
  - systemctl status docker
  - curl -L "https://github.com/docker/compose/releases/download/1.27.4/docker-compose-$(uname -s)-$(uname -m)" -o /usr/local/bin/docker-compose
  - chmod +x /usr/local/bin/docker-compose
  - docker-compose --version
  - docker search mongodb
  
  
  
  # Disable Cassandra optional extensions (faster testing).
  #- echo "deb http://debian.datastax.com/community stable main" | tee -a /etc/apt/sources.list.d/cassandra.sources.list
  #- curl -L http://debian.datastax.com/debian/repo_key | apt-key add -
  #- apt-get update
  #- apt-get -y install openjdk-8-jdk
  #- java -version
  #- apt-get -y install cassandra cython3
  #- bash travis/wait_for_cassandra.sh && \
  #- export CASS_DRIVER_NO_EXTENSIONS=1
  #- pip install -e .[test]
  #- if [[ $TRAVIS_PYTHON_VERSION == '3.6' || $TRAVIS_PYTHON_VERSION == '3.7' || $TRAVIS_PYTHON_VERSION == '3.8' || $TRAVIS_PYTHON_VERSION == 'nightly' ]]; then pip install -e .[experimental_aio]; fi
#before_script:
 # - bash travis/wait_for_cassandra.sh
#script:
  # Run non aio tests first because Python versions before 3.6 does not support aio.
  #- export DO_TEST_CASSANDRA=true
  #- nosetests --exclude-dir=test/aio
  # Run aio tests.
  #- export DO_TEST_MONGO=true
  #- if [[ $TRAVIS_PYTHON_VERSION == '3.6' || $TRAVIS_PYTHON_VERSION == '3.7' || $TRAVIS_PYTHON_VERSION == '3.8' || $TRAVIS_PYTHON_VERSION == 'nightly' ]]; then nosetests test.aio; fi
